UPDATED the behavior of , , TRAP, cleanup, and threads

diff --git a/functions/micapipe_qsub-test b/functions/micapipe_qsub-test
--- a/functions/micapipe_qsub-test
+++ b/functions/micapipe_qsub-test
@@ -16,10 +16,10 @@ BIDS=$1
 id=$2
 out=$3
 SES=$4
-PROC=$5
-nocleanup=$6
-threads=$7
-tmpDir=$8
+nocleanup=$5
+threads=$6
+tmpDir=$7
+PROC=$8
 here=$(pwd)
 export OMP_NUM_THREADS=$threads
 
@@ -52,10 +52,9 @@ aloita=$(date +%s)
 # Create script specific temp directory
 tmp=${tmpDir}/${RANDOM}_micapipe-test_${id}
 Do_cmd mkdir -p $tmp
-Info "Temporary directory: $tmp"
 
 # TRAP in case the script fails
-trap 'cleanup $tmp $here $nocleanup' SIGINT EXIT
+trap 'cleanup $tmp $nocleanup $here' SIGINT SIGTERM
 
 # GLOBAL variables for this script
 Info "Not erasing temporal dir: $nocleanup"
@@ -72,15 +71,15 @@ Note "SHELL             =" $SHELL
 Note "MICAPIPE          =" $MICAPIPE
 Note "AFNIDIR           =" $AFNIDIR
 Note "ANTSPATH          =" $ANTSPATH
-Note "MRtrix3 bin       =" "`which mrinfo`"
-Note "wb_command        =" "`which wb_command`"
+Note "MRtrix3 bin       =" "$(which mrinfo)"
+Note "wb_command        =" "$(which wb_command)"
 Note "FREESURFER_HOME   =" $FREESURFER_HOME
 Note "FSLDIR            =" $FSLDIR
 Note "FSL_BIN           =" $FSL_BIN
 Note "FIXPATH           =" $FIXPATH
 Note "FSLPARALLEL       =" $FSLPARALLEL
 
-Info "python: `python --version`"
+Info "python: $(python --version)"
 Note "PYTHONPATH        =" $PYTHONPATH
 Note "PYTHONHOME        =" $PYTHONHOME
 Note "LC_ALL            =" $LC_ALL
@@ -101,25 +100,25 @@ bids_print.variables-post
 
 #    PACKAGES DEPENDENCIES print versions
 # Dicom to nifti X converter
-if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; else Info "dcm2niix was found"; fi
+if [[ -z $(which dcm2niix) ]]; then Error "Check your dcm2niix installation"; else Info "dcm2niix was found"; fi
 # tree display
-if [[ -z `which tree` ]]; then Warn "tree function was not found"; else Info "tree version: `tree --version | awk '{print $2}'`"; fi
+if [[ -z $(which tree) ]]; then Warn "tree function was not found"; else Info "tree version: $(tree --version | awk '{print $2}')"; fi
 #  MRtrix3
-if [[ -z `which mrinfo` ]]; then Error "MRtrix3 was not found"; else Info "MRtrix3 version: `mrinfo -version | awk 'NR==1 {print $3}'`"; fi
+if [[ -z $(which mrinfo) ]]; then Error "MRtrix3 was not found"; else Info "MRtrix3 version: $(mrinfo -version | awk 'NR==1 {print $3}')"; fi
 # freesurfer
-if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; else Info "FreeSurfer version: `recon-all -version`"; fi
+if [[ -z $(which recon-all) ]]; then Error "FreeSurfer was not found"; else Info "FreeSurfer version: $(recon-all -version)"; fi
 # FSL
-if [[ -z `which flirt` ]]; then Error "FSL was not found"; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
+if [[ -z $(which flirt) ]]; then Error "FSL was not found"; else Info "FSL version: $(flirt -version | awk '{print $3}')"; fi
 # AFNI
-if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; else Info "AFNI version: `afni -version | awk -F ':' '{print $2}'`"; fi
+if [[ -z $(which 3dresample) ]]; then Error "AFNI was not found"; else Info "AFNI version: $(afni -version | awk -F ':' '{print $2}')"; fi
 # ANTSx
-if [[ -z `which antsRegistration` ]]; then Error "ANTs was not found"; else Info "ANTS version: `antsRegistration --version | awk -F ':' 'NR==1{print $2}'`"; fi
+if [[ -z $(which antsRegistration) ]]; then Error "ANTs was not found"; else Info "ANTS version: $(antsRegistration --version | awk -F ':' 'NR==1{print $2}')"; fi
 # workbench
-if [[ -z `which wb_command` ]]; then Error "WorkBench was not found"; else Info "workbench version: `wb_command -version | awk 'NR==3{print $2}'`"; fi
+if [[ -z $(which wb_command) ]]; then Error "WorkBench was not found"; else Info "workbench version: $(wb_command -version | awk 'NR==3{print $2}')"; fi
 # fix
-if [[ -z `which fix` ]]; then Warning "fix was not found, ICA-FIX will be skipped"; else Info "ICA-based Xnoiseifier was found here: `which fix`"; fi
+if [[ -z $(which fix) ]]; then Warning "fix was not found, ICA-FIX will be skipped"; else Info "ICA-based Xnoiseifier was found here: $(which fix)"; fi
 # R
-if [[ -z `which R` ]]; then Warning "R was not found"; else Info "R was found here: `which R`, version `R --version | awk 'NR==1{print $3}'`"; fi
+if [[ -z $(which R) ]]; then Warning "R was not found"; else Info "R was found here: $(which R), version $(R --version | awk 'NR==1{print $3}')"; fi
 
 
 # print the names on the terminal
@@ -128,8 +127,8 @@ bids_print.variables-dwi
 
 # Concatenate shells -if only one shell then just convert to mif and rename.
 for dwi in ${bids_dwis[@]}; do
-      dwi_nom=`echo $dwi | awk -F "dwi/" '{print $2}' | awk -F ".nii" '{print $1}'`
-      bids_dwi_str=`echo $dwi | awk -F . '{print $1}'`
+      dwi_nom=$(echo $dwi | awk -F "dwi/" '{print $2}' | awk -F ".nii" '{print $1}')
+      bids_dwi_str=$(echo $dwi | awk -F . '{print $1}')
       Do_cmd mrconvert $dwi -json_import ${bids_dwi_str}.json -fslgrad ${bids_dwi_str}.bvec ${bids_dwi_str}.bval ${tmp}/${dwi_nom}.mif
 done
 # Concatenate shells and convert to mif.
@@ -137,20 +136,21 @@ dwi_cat=${tmp}/dwi_concatenate.mif
 Do_cmd mrcat ${tmp}/*.mif $dwi_cat -nthreads $threads
 
 # Get parameters
-ReadoutTime=`mrinfo $dwi_cat -property TotalReadoutTime`
-pe_dir=`mrinfo $dwi_cat -property PhaseEncodingDirection`
+ReadoutTime=$(mrinfo $dwi_cat -property TotalReadoutTime)
+pe_dir=$(mrinfo $dwi_cat -property PhaseEncodingDirection)
 
 Info "dwifslpreproc parameters:"
-Note "Shell values        :" "`mrinfo $dwi_cat -shell_bvalues`"
-Note "DWI main dimensions :" "`mrinfo $dwi_cat -size`"
-Note "DWI shell values    :" "`mrinfo $dwi_cat -shell_bvalues`"
+Note "Shell values        :" "$(mrinfo $dwi_cat -shell_bvalues)"
+Note "DWI main dimensions :" "$(mrinfo $dwi_cat -size)"
+Note "DWI shell values    :" "$(mrinfo $dwi_cat -shell_bvalues)"
 Note "pe_dir              :" $pe_dir
 Note "Readout Time        :" $ReadoutTime
 
 # QC notification of completition
 lopuu=$(date +%s)
 eri=$(echo "$lopuu - $aloita" | bc)
-eri=`echo print $eri/60 | perl`
+eri=$(echo print $eri/60 | perl)
 
-Title "Running MICA qsub test ended in \033[38;5;220m `printf "%0.3f\n" ${eri}` minutes \033[38;5;141m"
-echo "${id}, MICAq-TEST, DONE, `whoami`, `uname -n`, $(date), `printf "%0.3f\n" ${eri}`, $PROC" #>> ${out}/brain-proc.csv
+echo -e "\n\n${id}, MICAq-TEST, DONE, $(whoami), $(uname -n), $(date), $(printf "%0.3f\n" ${eri}), $PROC" #>> ${out}/brain-proc.csv
+Title "Running MICA qsub test ended in \033[38;5;220m $(printf "%0.3f\n" ${eri}) minutes \033[38;5;141m"
+cleanup $tmp $nocleanup $here
