fixed check versions and exti 1

diff --git a/mica-pipe b/mica-pipe
--- a/mica-pipe
+++ b/mica-pipe
@@ -50,7 +50,7 @@ if [ -z "${MICAPIPE}" ]; then
 echo -e "\033[38;5;1m\n---------------------------------------------------------\n
 [ERROR]... MICAPIPE must be define in your enviroment\033[0m
            TRY: export MICAPIPE=<github_Directory>/micasoft\n
-\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 0
+\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 1
 fi
 
 if [ ! -f ${MICAPIPE}/functions/utilities.sh ]; then
@@ -59,7 +59,7 @@ echo -e "\033[38;5;1m\n---------------------------------------------------------
            it should match /micasoft directory\033[0m
            CHECK PATH to MICAPIPE:
            $MICAPIPE\n
-\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 0
+\033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 1
 fi
 
 # Source utilities functions from MICAPIPE
@@ -133,7 +133,7 @@ do
   -*)
     Error "Unknown option ${2}"
     help
-    exit
+    exit 1
   ;;
     esac
 done
@@ -145,7 +145,7 @@ Error "One or more mandatory arguments are missing:"
 Note "-sub " $id
 Note "-out " "$out"
 Note "-bids " "$BIDS"
-help; exit 0; fi
+help; exit 1; fi
 runs=($proc $procVOL $procFS $procDWI $post $postVOL $postDWI)
 if [ "${#runs[@]}" -lt 1 ]; then
 Error "A processing flag is missing:
@@ -156,7 +156,7 @@ Error "A processing flag is missing:
                     -post
                     -post_structural
                     -post_tractography"
-help; exit 0; fi
+help; exit 1; fi
 
 # Get the real path of the Inputs
 out=`realpath $out`
@@ -164,22 +164,22 @@ BIDS=`realpath $BIDS`
 
 # -----------------------------------------------------------------------------------------------#
 #    PACKAGES DEPENDENCIES print versions
-# others
-if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; exit 0; else Info "dcm2niix was found"; fi
-if [[ -z `which tree` ]]; then Warn "tree function was not found"; fi
-#  MRtrix3 - NOTE dwifslpreproc is from MRtrix 3.0.0, we have 3.0_RC3-178-g32afe60f
-#if [[ -z `which dwifslpreproc` ]]; then Error "MRtrix3 was not found"; exit 0; else Info "MRtrix3 version: `dwifslpreproc -version | awk 'NR==1 {print $3}'`"; fi
-if [[ -z `which mrconvert` ]]; then Error "MRtrix3 was not found"; exit 0; else Info "MRtrix3 version: `mrconvert -version | awk 'NR==1 {print $3}'`"; fi
+# Dicom to nifti X converter
+if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; exit 1; else Info "dcm2niix was found"; fi
+# tree display
+if [[ -z `which tree` ]]; then Warn "tree function was not found"; else Info "`tree --version | awk '{print $2}'`"; fi
+#  MRtrix3
+if [[ -z `which mrinfo` ]]; then Error "MRtrix3 was not found"; exit 1; else Info "MRtrix3 version: `mrinfo -version | awk 'NR==1 {print $3}'`"; fi
 # freesurfer
-if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; exit 0; else Info "FreeSurfer version: `recon-all -version`"; fi
+if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; exit 1; else Info "FreeSurfer version: `recon-all -version`"; fi
 # FSL
-if [[ -z `which flirt` ]]; then Error "FSL was not found"; exit 0; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
+if [[ -z `which flirt` ]]; then Error "FSL was not found"; exit 1; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
 # AFNI
-if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; exit 0; else Info "AFNI version: `afni -version | awk -F ':' '{print $1}'`"; fi
+if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; exit 1; else Info "AFNI version: `afni -version | awk -F ':' '{print $2}'`"; fi
 # ANTSx
-if [[ -z "${ANTSPATH}" ]]; then Error "ANTs was not found"; exit 0; else Info "ANTS binaries: $ANTSPATH"; fi
+if [[ -z `which antsRegistration` ]]; then Error "ANTs was not found"; exit 1; else Info "ANTS version: `antsRegistration --version | awk -F ':' 'NR==1{print $2}'`"; fi
 # workbench
-if [[ -z `which wb_command` ]]; then Error "WorkBench was not found"; exit 0; else Info "AFNI version: `afni -version | awk -F ':' '{print $1}'`"; fi
+if [[ -z `which wb_command` ]]; then Error "WorkBench was not found"; exit 1; else Info "workbench version: `wm_command -version | awk 'NR==3{print $2}; fi
 
 # Minc tool kit
 # Won't use minc tools in this release
@@ -194,7 +194,7 @@ if [[ ${force} == TRUE ]]; then
   rm -rf $out/${subject};
 fi
 if [ -d ${subject_dir} ]; then Warning "Output directory already exist, processing will continue.\n\t\t If you want to re-run everything use -force to overwrite it. \n\t\t ${subject_dir}"; fi
-if [ ! -d ${subject_bids} ]; then Error "$id was not found on the BIDS directory\n\t     ${subject_bids}"; exit 0; fi
+if [ ! -d ${subject_bids} ]; then Error "$id was not found on the BIDS directory\n\t     ${subject_bids}"; exit 1; fi
 
 # -----------------------------------------------------------------------------------------------#
 #			  Timer & Beginning
@@ -335,8 +335,8 @@ fi
 if [ "$post" = "TRUE" ] || [ "$postDWI" = "TRUE" ]; then
   T1nativepro_5tt=${subject_dir}/proc_struc/${id}_t1w_0.8mm_nativepro_5TT.nii.gz
   # Check REQUIREMENTS otherwise PASS
-  if [ ! -f ${T1nativepro} ]; then Error "-proc_volumetric outputs are missing"; exit 0; fi
-  if [ ! -f $T1nativepro_5tt ]; then Error "-proc_volumetric outputs are missing"; exit 0; fi
+  if [ ! -f ${T1nativepro} ]; then Error "-proc_volumetric outputs are missing"; exit 1; fi
+  if [ ! -f $T1nativepro_5tt ]; then Error "-proc_volumetric outputs are missing"; exit 1; fi
   # if DWI processed data is not here stop
 
     Title "Running POST structural processing: Tractography & Connectome generation"
