UPDATED bash syntax and threads in qtest

diff --git a/mica-pipe b/mica-pipe
--- a/mica-pipe
+++ b/mica-pipe
@@ -246,6 +246,10 @@ do
     atlas=$2
     shift;shift;
   ;;
+  -freesurfer_dir)
+    FSdir=$2
+    shift;shift;
+  ;;
   -qsub)
     micaq=TRUE
     shift
@@ -329,11 +333,11 @@ BIDS=$(realpath $BIDS)
 id=${id/sub-/}
 here=$(pwd)
 
-# Number of session (Default is "ses-pre")
-if [ -z ${SES} ]; then SES="ses-pre"; else SES="ses-${SES/ses-/}"; fi
+# Number of session (Default is "" Single session)
+if [ -z ${SES} ]; then SES="SINGLE"; else SES="ses-${SES/ses-/}"; fi
 
 # Check BIDS Directory
-if [ ! -d ${BIDS}/sub-${id}/${SES} ]; then Error "$id was not found on the BIDS directory\n\t Check ls ${BIDS}/sub-${id}/${SES}"; exit 1; fi
+if [ ! -d ${BIDS}/sub-${id} ]; then Error "$id was not found on the BIDS directory\n\t Check ls ${BIDS}/sub-${id}"; exit 1; fi
 
 # Erase temporal files by default
 if [ -z ${nocleanup} ]; then nocleanup=FALSE; fi
@@ -343,6 +347,9 @@ if [ "$quiet" = "TRUE" ]; then export quiet=TRUE; fi
 
 # Temporal directory
 if [ -z ${tmpDir} ]; then export tmpDir=/tmp; else tmpDir=$(realpath $tmpDir); fi
+
+# Freesurfer dir exits
+if [ -z ${FSdir} ]; then FSdir="FALSE"; else FSdir=$(realpath $FSdir); fi
 
 # -----------------------------------------------------------------------------------------------#
 Title "BIDS >> MICA pipeline processing \n\t\tSubject: $id Session: $SES"
@@ -402,7 +409,9 @@ if [ -d ${subject_dir} ]; then Warning "Output directory already exist, processi
 aloita=$(date +%s)
 
 # Create tmp dir
-if [ ! -d ${tmpDir}]; then Do_cmd mkdir -p $tmpDir; fi
+if [ ! -d ${tmpDir} ]; then
+    Do_cmd mkdir -p $tmpDir
+fi
 
 # -----------------------------------------------------------------------------------------------#
 #   subject_dir
@@ -426,14 +435,14 @@ if [ "$ALL" = "TRUE" ] || [ "$procVOL" = "TRUE" ]; then
     log_file_str=$dir_logs/proc-volumetric_$(date +'%d-%m-%Y')
     COMMAND="${scriptDir}/01_proc-struc_volumetric.sh $BIDS $id $out $SES $nocleanup $threads $tmpDir"
     # mica.q - Structural processing: Volumetric
-    if [[ $micaq == "TRUE" ]] ; then
+    if [[ $micaq == "TRUE" ]]; then
         Info "MICA qsub - Structural processing: Volumetric"
         Warning "This option only works on the MICA workstations"
         export PROC="qsub-MICA"
         # Info "Setting a warper to run on mica.q"
         qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_volumetric -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
     # all.q - Structural processing: Volumetric
-    elif [[ $qall == "TRUE" ]] ; then
+    elif [[ $qall == "TRUE" ]]; then
         Info "all.q qsub - Structural processing: Volumetric"
         Warning "This option only works on the McGill BIC network"
         export PROC="qsub-all.q"
@@ -449,7 +458,7 @@ fi
 # # #        Structural processing: Freesurfer
 if [ "$ALL" = "TRUE" ] || [ "$procFS" = "TRUE" ]; then
     log_file_str=$dir_logs/proc-freesurfer$(date +'%d-%m-%Y')
-    COMMAND="${scriptDir}/01_proc-struc_freesurfer.sh $BIDS $id $out $SES $nocleanup $threads $tmpDir"
+    COMMAND="${scriptDir}/01_proc-struc_freesurfer.sh $BIDS $id $out $SES $nocleanup $threads $tmpDir $FSdir"
     # mica.q - Structural processing: Freesurfer
     if [[ $micaq == "TRUE" ]] ; then
         Info "MICA qsub - Structural processing: Freesurfer"
