added rsfmri to processing flags, init into local mica -flag

diff --git a/mica-pipe b/mica-pipe
--- a/mica-pipe
+++ b/mica-pipe
@@ -40,6 +40,7 @@ Usage:  `basename $0`\033[0m  \033[38;5;197m-sub\033[0m <subject_id> \033[38;5;1
    MRtrix3     3.0.0   (https://www.mrtrix.org)
    ANTs        2.3.3   (https://github.com/ANTsX/ANTs)
    workbench 1.3.2
+   FIX (FMRIB's ICA-based Xnoiseifier) v1.06
    ENIGMA toolbox (https://github.com/MICA-MNI/ENIGMA)
 
 
@@ -48,27 +49,6 @@ https://github.com/MICA-MNI/micapipe
 http://mica-mni.github.io/
 "
 }
-
-# Launch the init file. (Note to Raul: this may make the next check obsolete - RV)
-script_path="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
-source $script_path/functions/init.sh
-if [[ $? != 0 ]]; then
-  echo -e "\033[38;5;1m\n---------------------------------------------------------\n
-  [ERROR]... Could not find init file. Is this script in the
-            base directory of the MICAPIPE github and in init
-            file in the functions subdirectory?
-  \033[38;5;1m---------------------------------------------------------\033[0m\n"; exit 1
-fi
-
-# ITS A TRAP! Specifically a trap that will reset the old user path upon exits,
-# interrupts, and termination. We could add a deletion of the temporary directory
-# here too.
-function cleanup() {
-  export PATH=$OLD_PATH
-  unset OLD_PATH
-  unset tmp
-}
-trap cleanup EXIT INT TERM
 
 # Check MICAPIPE
 if [ -z "${MICAPIPE}" ]; then
@@ -135,6 +115,10 @@ do
     procDWI=TRUE
     shift
   ;;
+  -proc_rsfmri)
+    procfMRI=TRUE
+    shift
+  ;;
   -post_structural)
     postVOL=TRUE
     shift
@@ -147,7 +131,11 @@ do
     postMPC=TRUE
     shift
   ;;
-  -micaq)
+  -mica)
+    mica=TRUE
+    shift
+  ;;
+  -qsub)
     micaq=TRUE
     shift
   ;;
@@ -175,13 +163,13 @@ Note "-sub " $id
 Note "-out " "$out"
 Note "-bids " "$BIDS"
 help; exit 1; fi
-runs=($proc $procVOL $procFS $procDWI $post $postVOL $postDWI $postMPC)
+runs=($proc $procVOL $procFS $procDWI $procfMRI $post $postVOL $postDWI $postMPC)
 if [ "${#runs[@]}" -lt 1 ]; then
 Error "A processing flag is missing:
                     -proc
                     -proc_volumetric
                     -proc_freesurfer
-                    -proc_surfpatch
+                    -proc_rsfmri
                     -post
                     -post_structural
                     -post_tractography
@@ -193,26 +181,42 @@ out=`realpath $out`
 BIDS=`realpath $BIDS`
 
 # -----------------------------------------------------------------------------------------------#
-#    PACKAGES DEPENDENCIES print versions
-# Dicom to nifti X converter
-if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; exit 1; else Info "dcm2niix was found"; fi
-# tree display
-if [[ -z `which tree` ]]; then Warn "tree function was not found"; else Info "`tree --version | awk '{print $2}'`"; fi
-#  MRtrix3
-if [[ -z `which mrinfo` ]]; then Error "MRtrix3 was not found"; exit 1; else Info "MRtrix3 version: `mrinfo -version | awk 'NR==1 {print $3}'`"; fi
-# freesurfer
-if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; exit 1; else Info "FreeSurfer version: `recon-all -version`"; fi
-# FSL
-if [[ -z `which flirt` ]]; then Error "FSL was not found"; exit 1; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
-# AFNI
-if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; exit 1; else Info "AFNI version: `afni -version | awk -F ':' '{print $2}'`"; fi
-# ANTSx
-if [[ -z `which antsRegistration` ]]; then Error "ANTs was not found"; exit 1; else Info "ANTS version: `antsRegistration --version | awk -F ':' 'NR==1{print $2}'`"; fi
-# workbench
-if [[ -z `which wb_command` ]]; then Error "WorkBench was not found"; exit 1; else Info "workbench version: `wb_command -version | awk 'NR==3{print $2}'`"; fi
-# Minc tool kit
-# Won't use minc tools in this release
-#if [[ -z `which mincgen` ]]; then Warning "Minc Tool Kit was not found, proceed with caution"; else Info "Minc version: `mincgen -version | awk 'NR==1{print $2}'`"; fi
+# init file for local processing at MICA lab
+if [ "$micaq" = "TRUE" ] || [ "$mica" = "TRUE" ]; then
+    # Launch the init file.
+    source ${MICAPIPE}/functions/init.sh
+    if [[ $? != 0 ]]; then
+      Error "Could not find init file. Is this script in the\n base directory of the MICAPIPE github and in init \nfile in the functions subdirectory?"; exit 1
+    fi
+    # ITS A TRAP! Specifically a trap that will reset the old user path upon exits,
+    # interrupts, and termination. We could add a deletion of the temporary directory
+    # here too.
+    function cleanup() {
+      export PATH=$OLD_PATH
+      unset OLD_PATH
+      unset tmp
+    }
+    trap cleanup EXIT INT TERM
+else
+    # -----------------------------------------------------------------------------------------------#
+    #    PACKAGES DEPENDENCIES print versions
+    # Dicom to nifti X converter
+    if [[ -z `which dcm2niix` ]]; then Error "Check your dcm2niix installation"; exit 1; else Info "dcm2niix was found"; fi
+    # tree display
+    if [[ -z `which tree` ]]; then Warn "tree function was not found"; else Info "`tree --version | awk '{print $2}'`"; fi
+    #  MRtrix3
+    if [[ -z `which mrinfo` ]]; then Error "MRtrix3 was not found"; exit 1; else Info "MRtrix3 version: `mrinfo -version | awk 'NR==1 {print $3}'`"; fi
+    # freesurfer
+    if [[ -z `which recon-all` ]]; then Error "FreeSurfer was not found"; exit 1; else Info "FreeSurfer version: `recon-all -version`"; fi
+    # FSL
+    if [[ -z `which flirt` ]]; then Error "FSL was not found"; exit 1; else Info "FSL version: `flirt -version | awk '{print $3}'`"; fi
+    # AFNI
+    if [[ -z `which 3dresample` ]]; then Error "AFNI was not found"; exit 1; else Info "AFNI version: `afni -version | awk -F ':' '{print $2}'`"; fi
+    # ANTSx
+    if [[ -z `which antsRegistration` ]]; then Error "ANTs was not found"; exit 1; else Info "ANTS version: `antsRegistration --version | awk -F ':' 'NR==1{print $2}'`"; fi
+    # workbench
+    if [[ -z `which wb_command` ]]; then Error "WorkBench was not found"; exit 1; else Info "workbench version: `wb_command -version | awk 'NR==3{print $2}'`"; fi
+fi
 
 # LOADS variables with the BIDS format
 bids_variables $BIDS $id $out
@@ -247,7 +251,7 @@ export util_surface=${MICAPIPE}/surfaces # utilities/resample_fsaverage
 # Creates subject directory if it doesn't exist
 if [ ! -d ${subject_dir} ]; then
     Info "Subject ${id} directory doesn't exist"
-    Do_cmd mkdir -p $subject_dir/{logs,xfms,proc_dwi,proc_struct/{first,volumetric,surfpatch,surfaces/{conte69,$id}}}
+    Do_cmd mkdir -p $subject_dir/{logs,xfms,proc_dwi,proc_struct,proc_rsfmri/{first,volumetric,surfpatch,surfaces/{conte69,$id}}}
 else
     Info "Subject ${id} directory exist"
 fi
@@ -265,27 +269,19 @@ if [ "$proc" = "TRUE" ] || [ "$procVOL" = "TRUE" ]; then
     if [[ $micaq == "TRUE" ]] ; then
       Warning "This option only works on the MICA workstations, for now..."
       Warning "This step is NOT implemented yet, mica.q script is not functional"
+      tmp="micaq"
       # mmTemplates="0.8 2" ### MNI152 templates resolutions
       # t1Scans=$(find $subject_bids/anat/ -name "*ses-pre_run-?_T1w.nii.gz" )
       # t1ScansCmd=$(echo "-t $(echo $t1Scans | sed 's: : -t :g')")
       # Info "Setting a warper to run on mica.q"
-      # if [[ -z $(mica_qget names . . "*" | grep ${id}_structuralVolumetric) ]] ; then
-      #     rm -fv $dir_logs/structuralVolumetric.txt
-      #     qsub \
-      #         -q mica.q \
-      #         -l h_vmem=6G \
-      #         -N ${id}_structuralVolumetric \
-      #         -e $dir_logs/structuralVolumetric.txt \
-      #         -o $dir_logs/structuralVolumetric.txt \
-      #         -hold_jid ${id}_dicom2bids \
-      #         $scriptDir/01_proc-struc_volumetric-MTL.sh \
-      #         -n -p SETDEFAULT $t1ScansCmd \
-      #         "0.8 2" \
-      #         $proc_struct \
-      #         $dir_warp \
-      #         $util_MNIvolumes \
-      #         $dir_first \
-      #         $id
+      # qsub \
+      #      -q mica.q \
+      #      -l h_vmem=6G \
+      #      -N ${id}_structuralVolumetric \
+      #      -e $dir_logs/structuralVolumetric.txt \
+      #      -o $dir_logs/structuralVolumetric.txt \
+      #      -hold_jid ${id}_dicom2bids \
+      #      ${scriptDir}/01_proc-struc_volumetric.sh $BIDS $id $out $tmp
       else
       #   Structural processing: Volumetric
       # the $4 argument is the tmp directory where processes will run default is /tmp
@@ -331,12 +327,6 @@ if [ "$proc" = "TRUE" ] || [ "$procDWI" = "TRUE" ]; then
 fi
 
 # -----------------------------------------------------------------------------------------------#
-# # #        Resting state
-# -----------------------------------------------------------------------------------------------#
-#  Resting state
-
-
-# -----------------------------------------------------------------------------------------------#
 #                   POST Structural processing mica-02
 # -----------------------------------------------------------------------------------------------#
 # # #         POST Structural processing
@@ -354,6 +344,25 @@ if [ "$post" = "TRUE" ] || [ "$postVOL" = "TRUE" ]; then
       #  POST-Structural processing
       # the $4 argument is the tmp directory where processes will run default is /tmp
       ${scriptDir}/02_post-structural.sh $BIDS $id $out 2>&1 | tee -a  ${dir_logs}/post_structural.txt
+    fi
+fi
+
+# -----------------------------------------------------------------------------------------------#
+# # #        Resting state
+# -----------------------------------------------------------------------------------------------#
+#  Resting state
+if [ "$procfMRI" = "TRUE" ]; then
+    Title "Running Resting State fMRI processing"
+    # SGE -qsub TRUE
+    if [[ $micaq == "TRUE" ]] ; then
+      Warning "This option only works on the MICA workstations, for now..."
+      Warning "This step is NOT implemented yet, mica.q script is not functional"
+      # Info "Setting a warper to run on mica.q"
+      # ...../ missing implementation
+    else
+      #  POST-Structural processing
+      # the $4 argument is the tmp directory where processes will run default is /tmp
+       ${scriptDir}/03_proc_rsfmri.sh $BIDS $id $out 2>&1 | tee -a  ${dir_logs}/proc_rsfmri.txt
     fi
 fi
 
